"""
Dockerfile and functions.yml Renderer

SAMテンプレートから抽出した関数情報をもとに、
DockerfileとFunctions.ymlを生成します。
"""

from pathlib import Path
from jinja2 import Environment, BaseLoader


# Dockerfile テンプレート
DOCKERFILE_TEMPLATE = """\
# Auto-generated by SAM Template Generator
# DO NOT EDIT MANUALLY - Regenerate with: python -m tools.generator.main
# Source: template.yaml

FROM public.ecr.aws/lambda/python:{{ python_version }}

# ---------------------------------------------------
# ローカル実行用パッチの注入
# ---------------------------------------------------
COPY {{ sitecustomize_source }} /var/lang/lib/python{{ python_version }}/site-packages/

{% if has_requirements %}
# ---------------------------------------------------
# 関数固有の依存パッケージ
# ---------------------------------------------------
COPY {{ code_uri }}requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt

{% endif %}
# ---------------------------------------------------
# 関数コードの配置
# ---------------------------------------------------
COPY {{ code_uri }}*.py ${LAMBDA_TASK_ROOT}/

# ---------------------------------------------------
# ハンドラ指定
# ---------------------------------------------------
CMD [ "{{ handler }}" ]
"""


def render_dockerfile(
    func_config: dict,
    docker_config: dict,
) -> str:
    """
    Dockerfileをレンダリングする
    
    Args:
        func_config: 関数設定
            - name: 関数名
            - code_uri: コードパス
            - handler: ハンドラ
            - runtime: ランタイム (e.g., 'python3.12')
            - has_requirements: requirements.txt があるか
        docker_config: Docker設定
            - sitecustomize_source: sitecustomize.pyのパス
    
    Returns:
        Dockerfile文字列
    """
    env = Environment(loader=BaseLoader())
    template = env.from_string(DOCKERFILE_TEMPLATE)
    
    # ランタイムからPythonバージョンを抽出 (e.g., 'python3.12' -> '3.12')
    runtime = func_config.get('runtime', 'python3.12')
    python_version = runtime.replace('python', '')
    
    context = {
        'python_version': python_version,
        'sitecustomize_source': docker_config.get('sitecustomize_source', 'lib/sitecustomize.py'),
        'code_uri': func_config.get('code_uri', './'),
        'handler': func_config.get('handler', 'lambda_function.lambda_handler'),
        'has_requirements': func_config.get('has_requirements', False),
    }
    
    return template.render(context)


def render_functions_yml(
    functions: list[dict],
    base_config: dict | None = None,
) -> str:
    """
    functions.yml をレンダリングする
    
    Args:
        functions: 関数リスト
            - name: 関数名
            - environment: 環境変数辞書
        base_config: ベース設定（defaults セクション）
    
    Returns:
        functions.yml文字列
    """
    import yaml
    
    if base_config is None:
        base_config = {}
    
    output = {}
    
    # defaults セクションをコピー
    if 'defaults' in base_config:
        output['defaults'] = base_config['defaults']
    
    # functions セクションを構築
    output['functions'] = {}
    for func in functions:
        name = func['name']
        env = func.get('environment', {})
        
        if env:
            output['functions'][name] = {'environment': env}
        else:
            output['functions'][name] = {}
    
    # YAML出力
    # ヘッダーコメント + YAML
    header = """\
# Auto-generated by SAM Template Generator
# DO NOT EDIT MANUALLY - Regenerate with: python -m tools.generator.main

"""
    return header + yaml.dump(output, sort_keys=False, allow_unicode=True, default_flow_style=False)
